version: '3.8'

services:
  db:
    container_name: postgresql
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    container_name: shareIt-server
    build: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SHAREIT_SERVER_PORT=9090
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432

  gateway:
    container_name: shareIt-gateway
    build: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_GATEWAY_PORT=8080
      - SHAREIT_SERVER_URL=http://server:9090